### ISSUE TITLE
instalation

### ISSUE THREAD

**Issue by parsibox** [Amir-Mehrpanah/atumated_lp#1]
hi
can you explain more how install it ?

**Comment by Amir-Mehrpanah** [comment]
hello yes, for sure.
just briefly tell me where your problem is. are/have you:
1. on win/Linux machine?
2. installed python?
3. cloned the repo?
4. [installed dependencies](https://github.com/Amir-Mehrpanah/persian_licenceplate_generator#how-to-use)

**Comment by parsibox** [comment]
i have centos  and windows ( both )
i install python
which opencv this need?

**Comment by Amir-Mehrpanah** [comment]
the ``OpenCV-python`` package is used it can be found [here](https://pypi.org/project/opencv-python/). by the way, all requirements are in the ``requirements.txt`` file
and it can be installed by the following command: (you don't need to install them one by one)
``pip3 install --upgrade -r requirements.txt``  ( on Linux)
``pip install --upgrade -r requirements.txt``  ( on windows)
good luck.:beers:

**Comment by parsibox** [comment]
thanks i am going to test it
thanks

**Comment by parsibox** [comment]
it say :

```
 python3.6 main.py 

init components...
libpng warning: iCCP: known incorrect sRGB profile

loading backgrounds (pack 0)...
0it [00:00, ?it/s]

generating 100 images.
  0%|                                                                                                                                                                                      | 0/100 [00:00<?, ?it/s]
loading backgrounds (pack 0)...
0it [00:00, ?it/s]
  0%|                                                                                                                                                                                      | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    plate = plate_generator.fill_background(plate)
  File "/home/mohsen/persian_licenceplate_generator/plate_generator.py", line 34, in fill_background
    bg = self.asset_manager.get_nxt_background()
  File "/home/mohsen/persian_licenceplate_generator/asset_manager.py", line 114, in get_nxt_background
    image = self.__backgrounds[self.__bg_counter]
IndexError: list index out of range
[mohsen@localhost persian_licenceplate_generator]$ 

```

**Comment by Amir-Mehrpanah** [comment]
I couldn't push my background images to this repo (because they may take a huge size and make cloning tedious).
you need to download many random images from google and cut them 1024 by 1024 (your "output size"). Size of the background images sould be equal to your output size which is in the ``project_configurations.jsonnet`` file:
``` c++
"transformations_config": {
    "output_size": [1024,1024],    // here 
    "max_dalpha": PI / 4,
    "max_dbeta": PI / 4,
    "max_dgamma": PI / 6,
    "max_dz": 3.5 // min_dz = 1
  },
```
after downloading and cutting background images, place them in the ``components/backgrounds/`` directory. This address, also, can be found in the ``project_configurations.jsonnet`` file:
```c++
"components": {
    "dirt": "components/dirt/*.png",
    "letters": "components/letters/*.png",
    "mini_numbers": "components/mini_numbers/*.png",
    "misc": "components/misc/*.png",
    "numbers": "components/numbers/*.png",
    "plates": "components/plates/*.png",
    "backgrounds": "components/backgrounds/*.jpg" // here
  }
```

**Comment by parsibox** [comment]
ok i run it with no error and in my output folder create to many image with plate number.
but after this with which project our code i can detect plate number in image?
do you have any other project for detect plate number ?
can you explain how can train CNN with your output image and use that for detect plate?( Please forgive me I am a rookie and I do not know the process )

**Comment by Amir-Mehrpanah** [comment]
There are many challenges in the process of training a CNN, one of which is preparing a data set. This repo is supposed to help you in the first step (so this issue should be closed if you have successfully completed the first step).
After this, you should search for some resources,[like this](https://medium.com/analytics-vidhya/training-your-own-data-set-using-mask-r-cnn-for-detecting-multiple-classes-3960ada85079), that help you train your own CNN. Keep trying you have a long way to go!

**Comment by parsibox** [comment]
thanks a lot
